name: CI with Codacy Quality Check
# Trigger test
# Trigger the workflow whenever code is pushed or a PR is made to main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Codacy Analysis CLI
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/src \
          codacy/codacy-analysis-cli \
          analyze --tool pylint --output results.json
